"""Meadow package."""

from meadow.config import (
    BackendMode,
    BackendSettings,
    CoachSettings,
    DEFAULT_CONFIG_PATH,
    GameSettings,
    LLMProviderSettings,
    LLMSettings,
    OpenRouterSettings,
    ProjectConfig,
    TelegramSettings,
    WebSettings,
    load_project_config,
)
from meadow.backend import ActorRef, ManagedTableConfig, TableBackend
from meadow.backend.http import HttpBackendClient
from meadow.backend.service import LocalBackendClient, LocalTableBackendService
from meadow.orchestrator import GameOrchestrator
from meadow.poker.decks import (
    DeckSequenceFactory,
    OrderedDeck,
    OrderedDeckFactory,
    ShuffledDeckFactory,
    decode_card_order,
    encode_card_order,
)
from meadow.poker.engine import PokerEngine
from meadow.replay import HandReplayBuildError, HandReplaySession, validate_hand_trace
from meadow.telegram_app import TelegramApp, TelegramAppConfig
from meadow.web_app import WebApp, WebAppConfig
from meadow.types import (
    ActionResult,
    ActionType,
    ActionValidationError,
    AutomaticProgressResult,
    DecisionRequest,
    GameEvent,
    GamePhase,
    HandArchive,
    HandRecord,
    HandSeatState,
    HandStateSnapshot,
    HandRecordStatus,
    HandRunResult,
    HandTrace,
    HandTransition,
    LegalAction,
    PlayerAction,
    PlayerView,
    PublicTableView,
    ReplayFrame,
    SeatConfig,
    TableConfig,
    TelegramTableState,
)

__all__ = [
    "ActionResult",
    "ActionType",
    "ActionValidationError",
    "ActorRef",
    "AutomaticProgressResult",
    "BackendMode",
    "BackendSettings",
    "CoachSettings",
    "DEFAULT_CONFIG_PATH",
    "DecisionRequest",
    "GameSettings",
    "GameEvent",
    "GameOrchestrator",
    "GamePhase",
    "HandArchive",
    "HandRecord",
    "HandReplayBuildError",
    "HandReplaySession",
    "HandSeatState",
    "HandStateSnapshot",
    "HandRecordStatus",
    "HandRunResult",
    "HandTrace",
    "HandTransition",
    "LegalAction",
    "LLMProviderSettings",
    "LLMSettings",
    "LocalBackendClient",
    "LocalTableBackendService",
    "ManagedTableConfig",
    "OpenRouterSettings",
    "PlayerAction",
    "PlayerView",
    "PokerEngine",
    "ProjectConfig",
    "PublicTableView",
    "ReplayFrame",
    "SeatConfig",
    "TableConfig",
    "TelegramSettings",
    "TelegramApp",
    "TelegramAppConfig",
    "TelegramTableState",
    "TableBackend",
    "WebApp",
    "WebAppConfig",
    "WebSettings",
    "HttpBackendClient",
    "DeckSequenceFactory",
    "OrderedDeck",
    "OrderedDeckFactory",
    "ShuffledDeckFactory",
    "decode_card_order",
    "encode_card_order",
    "load_project_config",
    "validate_hand_trace",
]
